### ISSUE TITLE
Keyboard shortcut for 'Send line to FSI' means you can't type '\' on OSX

### ISSUE THREAD

**Issue by rojepp** [fsprojects/atom-fsharp#92]
At least on OSX / Swedish. XS for this command is Ctrl-CMD-L.
For F# 4, they intended to remove this command from VS, but reinstated it (breaking change...)
The thought was that, iof selection length is zero, send the line. Otherwise, send the selection.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in version `0.7.3` - on Mac `Ctrl-CMD-L` is used. I think it could be nice to provide same key bindings as in XS for Mac - but I don't have Mac so would appreciate PR for it ;) 

Place to add those bindings - https://github.com/fsprojects/atom-fsharp/blob/develop/src/atom-fsharp/keymaps/core.cson#L19-L20

**Comment by rojepp** [comment]
I can verify that `Ctrl-CMD-L` works, but the Windows shortcut is still in effect, so I can't type `\`.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `0.8.1`
